### ISSUE TITLE
exporter silently fail.

### ISSUE THREAD

**Issue by cryptolukas** [terjesannum/tibber-exporter#21] opened 2024-08-28 07:35 UTC
Hi, the last days the exporter dies silently once per day.
The exporter is running or failing with a 404. 
I cannot see an indication why this happens.

These are the last loglines and nothing more.
```
2024/08/28 07:25:33 Updating HOURLY data for foobar
2024/08/28 07:25:33 Updating DAILY data for foobar```

**Comment by terjesannum** [comment] 2024-09-04 18:51
I checked the logs for my own home and see the same on that time. So this is most likely caused by something on the Tibber servers. This can happens quite often, that why it is important to run the exporter with automatic restart (https://github.com/terjesannum/tibber-exporter?tab=readme-ov-file#running). With that the exporter should resume working fine as soon as the Tibber services are working again.

So I'm closing this issue, please reopen if your exporter doesn't recover from these situations.

**Closed as completed by terjesannum** 2024-09-04 18:51 UTC
